spring.application.name=products
server.port=0

spring.mongodb.uri=mongodb+srv://bdd6230zAbioAKpw:et62L5xALk33CIxU@cluster0.rrdaalm.mongodb.net/?appName=Cluster0
spring.mongodb.database=spring_mongo_products

eureka.client.service-url.defaultZone=http://localhost:8761/eureka